apiVersion: v1
kind: Service
metadata:
  name: clustercost-dashboard
  labels:
    app: clustercost-dashboard
spec:
  type: ClusterIP
  selector:
    app: clustercost-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
